# .travis.yml
language: node_js

node_js:
 - 12.20.0
branchs:
 only:
  - master 
install:
- yarn

script: 
- yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  on:
    branch: master
