name: Deploy Dumi Blog to GitHub Pages

on:
  push:
    branches:
      - master  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12.20.0'  # 设置 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Build the Dumi site
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Dumi 的构建输出目录是 dist
